app:
  topic:
    name: ${APP_TOPIC_NAME:demo-topic}
    name-tx: ${APP_TOPIC_NAME_TX:demo-topic-tx}
    partitions: ${APP_TOPIC_PARTITIONS:#{null}}
    replicas: ${APP_TOPIC_REPLICATIONS:#{null}}
    min-insync-replicas: ${APP_TOPIC_MIN_INSYNC_REPLICAS:#{null}}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.apache.kafka: WARN
    org.springframework.kafka: INFO

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics

server:
  port: ${SERVER_PORT:8080}
  tomcat:
    connection-timeout: 5s
    keep-alive-timeout: 5s

spring:
  application:
    name: demo-service                              # Logical name of the Spring Boot application
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}    # Initial brokers used to discover the Kafka cluster
    admin:
      auto-create: true                             # Allows to create topics from Spring beans, even if broker auto-create is disabled, filling in any unspecified settings from broker defaults
      fail-fast: true                               # Allows the application to start even if Kafka is not reachable at startup
    listener:    # Configures default ConcurrentKafkaListenerContainerFactory
      missing-topics-fatal: false                   # Prevents the application from failing if topics do not exist yet
      ack-mode: manual                              # Offsets are committed only when ack.acknowledge() is called; not automatically or as part of a transaction
    producer:    # Configures default ProducerFactory → KafkaTemplate
      acks: all                                     # Wait for all in-sync replicas to acknowledge writes
      retries: 600                                  # Number of retries for temporary failures (retries for 600x500ms=5m)
      properties:
        max.block.ms: 1000                          # Limits how long the producer blocks during startup when Kafka is unavailable
        retry.backoff.ms: 500                       # Waits 500ms between retries to avoid flooding the broker
        linger.ms: 10                               # Wait up to 10ms to batch messages for higher throughput
        enable.idempotence: true                    # Prevents duplicate messages when retries occur, enables exactly-once semantics
        max.in.flight.requests.per.connection: 5    # Ensures message order when using idempotence
    consumer:    # Configures default ConsumerFactory
      group-id: demo-group
      auto-offset-reset: earliest                   # Start consuming from the oldest record if no committed offset exists (e.g. first start or offset lost)
      enable-auto-commit: false                     # Offsets are never committed automatically; commit occurs only via transaction or manually with acknowledgment
      isolation-level: read_committed               # Only read records from committed transactions
      properties:
        reconnect.backoff.ms: 1000                  # Controls how quickly the consumer retries connecting to Kafka
        reconnect.backoff.max.ms: 10000             # Limits the maximum delay between reconnect attempts
